# Generated by Django 2.1.5 on 2019-02-14 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0003_kit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_admin.Supplier'),
        ),
    ]
