# Generated by Django 2.1.5 on 2019-02-14 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0004_item_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='supplier',
        ),
    ]
